// PLEASE DO NOT EDIT THIS FILE
require('dotenv').config();
const { MongoClient } = require('mongodb');

async function main(callback) {
    const URL = process.env.MONGO_URL; // MONGO_URL should be declared in your .env file
    const client = new MongoClient(URL, { useNewUrlParser: true, useUnifiedTopology: true });

    try {
        // Connect to the MongoDB cluster
        await client.connect();

        // Make the appropriate DB calls
        await callback(client);

    } catch (e) {
        // Catch any errors
        console.error(e);
        throw new Error('Unable to Connect to Database')
    }
}

module.exports = main;